### ISSUE TITLE
Vala generates invalid code with SimpleType structures defined as arrays

### ISSUE THREAD

**Issue by smx-smx** [smx-smx/vala#2]
Such cases would cover structs that are passed by value rather than address
e.g.

```C
typedef CGLM_ALIGN(16) float vec4[4];
typedef vec4 mat4[4];

glm_mat4_identity(mat4 mat);
```

mat4 is effectively a struct of 16 floats.
To use such a struct in Vala one needs to do

```vala
[CCode(cname = "float *", cprefix = "glm_mat4_")]
public struct Matrix4 {
```

so that Vala will pass "pointer to Matrix4 instance" as float**
This has several caveats tho which make it not usable without hacks

 - sizeof(Matrix4) will match sizeof(float *)
 - Matrix4 objects will as such have an improper allocated space. This means one needs to have an auxiliary function, in C, that will do something like this

```C
extern inline void glm_mat4_init(float **mat4){
	*mat4 = calloc(16, sizeof(float));
}
```

Which means wrecking the automatic vala refcounting and possibly causing a leak.
Even with the above function i wasn't getting the proper allocation either, so a proper fix in Vala is desired.

Such fix would indicate wether we should pass a pointer to Struct/Class or pass it by value

**Comment by smx-smx** [comment]
19a2b791ec4c388254bdb5e6fdcbf530f111b927 fixes this, by allowing unassigned structs, but i'm not sure if it could be done in a better way

The following previously unbuildable code now works properly

```vala
using CGlm;
void main() {
        Matrix4 mat;

        float det = mat.det();
        stdout.printf("Determinant: %.2f\n", det);
}
```

`mat` is used undefined, because it is a SimpleType struct (and as such, passed by value) and has a default value emitted in C due to the following vapi declaration

```vala
[SimpleType, CCode(cname = "mat4", cprefix = "glm_mat4_", default_value = "GLM_MAT4_IDENTITY_INIT")]
        public struct Matrix4 {
```

**Comment by astavale** [comment]
If you need to initialize `mat` then should it not be like this?:
`Matrix4 mat = {};`
Simply declaring the type, `Matrix4 mat;`, allows the multi-dimensional array to be used as a return value. So it is initialized by the callee function and passed back by value to the caller. e.g.:

```
Matrix4 mat;
try { mat = process_me (x, y);
} catch (Error error) {
print ("Unable to process because %s", error.message);
}
```
There is no need to have an additional call to set a default value.

Binding multi-dimensional arrays should be possible in Vala. Can you take this over to the Vala bugzilla?

**Comment by smx-smx** [comment]
Thanks for taking a look.
Using `{}` as Struct initializer works on an unmodified vala compiler, but the resulting code won't build properly.
That's because now Vala treats all assignments of the struct as
`dest = source`

Problem is that doesn't work if the struct being moved is an array like in this case. GCC will stop with many lines reading
`error: assignment to expression with array type`

> C11, chapter §6.5.16
> assignment operator shall have a modifiable lvalue as its left operand.


In this case, we should be able to specify a manually defined copy function, but using `[CCode(copy_function = ...)]` doesn't seem to work with SimpleType structures and it gets ignored.

Even if it wasn't ignored, the problem is that Vala expects a copy function with the following prototype:
`foo *foo_copy(foo *source)`, which takes a `foo`, allocates a copy and returns the new copied element.

Problem in this case is that we cannot return an array within a C function, but only a pointer to it.

So we would need a specific copy function in cglm style, like
`void foo_copy(foo source, foo dest)` and Vala allocates a temporary variable on the stack for `dest`

Such copy function is useless for non-array types, since it would just receive their values. For those, we can either invoke the function as
`foo_copy(source, &dest);`
or we can emit an error such as

> error: cannot use copy_function for non-array SimpleType structure

In the end, the resulting generated code should be:
```C
mat4 source;
mat4 dest;
glm_mat4_copy(source, dest);
```

**Comment by smx-smx** [comment]
Also, it would be interesting to figure out why, when using `{}` as initializer, the value is copied twice in the generated C code, like this:

Original
```C
void _vala_main (void) {
        mat4 mat = GLM_MAT4_IDENTITY_INIT;
        gfloat det = 0.0F;
        gfloat _tmp0_;
        FILE* _tmp1_;
        mat = GLM_MAT4_IDENTITY_INIT;
        _tmp0_ = glm_mat4_det (mat);
        det = _tmp0_;
        _tmp1_ = stdout;
        fprintf (_tmp1_, "Determinant: %.2f\n", (gdouble) det);
}
```

Without explicit initialization (19a2b791ec4c388254bdb5e6fdcbf530f111b927)
```C
void _vala_main (void) {
        mat4 mat = GLM_MAT4_IDENTITY_INIT;
        gfloat det = 0.0F;
        gfloat _tmp0_;
        FILE* _tmp1_;
        _tmp0_ = glm_mat4_det (mat);
        det = _tmp0_;
        _tmp1_ = stdout;
        fprintf (_tmp1_, "Determinant: %.2f\n", (gdouble) det);
}
```
